import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { z, id, revision, page, paginate, operation as op, makeProduct } from './runtime.mjs';
import { FielddeckService } from '../service.mjs';
import { validateDeck, SKILLS, STARTERS } from '../public/model.js';
import { WORKSPACE_LIMITS, revisionOf } from '../lib/workspace.js';
import { fault, fingerprint, writeJSON, restorePreview } from './workspace.mjs';
import { deck as deckSchema, brief as briefSchema, slide as slideSchema } from './schemas.mjs';
const service = async ctx => new FielddeckService(ctx.root).open();
const change = { id, revision, dryRun: z.boolean().default(false) };
const object = z.record(z.string(), z.unknown());
const slidePatch = z.strictObject(Object.fromEntries(Object.entries(slideSchema.shape).map(([key, field]) => [key, (field instanceof z.ZodDefault ? field.removeDefault() : field).optional()])));
const operations = {
  'workspace.status': op('Inspect decks, limits and explicit legacy migration requirements.', {}, async (_, ctx) => { const s = await service(ctx); return { revision: fingerprint(s.workspace || s.legacy), migrationRequired: !s.workspace, ...(s.legacy ? { legacyRevision: revisionOf(s.legacy) } : {}), limits: WORKSPACE_LIMITS }; }),
  'workspace.backup': op('Export all decks, briefs, archives and checkpoints. Includes private notes.', { includePrivate: z.literal(true) }, async (_, c) => { const s = await service(c); s.ready(); const backup = { format: 'fielddeck-workspace', version: 1, workspace: s.workspace, sha256: fingerprint(s.workspace) }; const bytes = Buffer.from(JSON.stringify(backup)); return { artifact: { filename: 'fielddeck-private-workspace.json', mediaType: 'application/json', bytes: bytes.length, sha256: fingerprint(bytes), base64: bytes.toString('base64') } }; }),
  'workspace.restore': op('Preview or restore a full private library, retaining a recovery copy. Confirmation requires the returned previewToken.', { backup: object, expectedRevision: z.string().length(64), dryRun: z.boolean().default(true), confirm: z.boolean().default(false), previewToken: z.string().uuid().optional() }, async (i, c) => { const s = await service(c); s.ready(); if (fingerprint(s.workspace) !== i.expectedRevision) throw fault('CONFLICT', 'Workspace changed; preview again.', 409); if (i.backup.format !== 'fielddeck-workspace' || i.backup.version !== 1 || fingerprint(i.backup.workspace) !== i.backup.sha256) throw fault('INVALID_BACKUP', 'Backup format or hash mismatch.'); const { validateWorkspace } = await import('../lib/workspace.js'); const next = validateWorkspace(i.backup.workspace); const previewToken = await restorePreview(c.root, i, i.expectedRevision); if (i.dryRun) return { valid: true, deckCount: next.decks.length, previewToken, dryRun: true }; await writeJSON(path.join(c.root, `before-restore-${fingerprint(s.workspace)}.json`), { format: 'fielddeck-workspace', version: 1, workspace: s.workspace, sha256: fingerprint(s.workspace) }); for (const e of next.decks) e.counter = Math.max(e.counter, s.workspace.decks.find(old => old.deck.id === e.deck.id)?.counter || 0) + 1; await s.save(next); return { restored: true, revision: fingerprint(s.workspace) }; }, { write: true, destructive: true }),
  'workspace.migrate': op('Preserve the legacy deck, then explicitly initialize the deck library.', { revision, confirm: z.literal(true) }, async (i, c) => (await service(c)).migrate(i.confirm, i.revision), { write: true }),
  'deck.list': op('List deck metadata without private slide notes.', page, async (i, c) => paginate((await service(c)).list(), i)),
  'deck.get': op('Read an editable deck with its revision. Contains private speaker notes.', { id }, async (i, c) => (await service(c)).get(i.id)),
  'deck.create': op('Create an independent deck. Reuse requestId to detect a retry without creating duplicates.', { title: z.string().trim().min(1).max(140), starter: z.enum(['blank', 'sample', ...STARTERS]).default('blank'), brief: briefSchema.nullable().default(null), deck: deckSchema.optional(), requestId: z.string().uuid(), dryRun: z.boolean().default(false) }, async (i, c) => (await service(c)).create(i), { write: true }),
  'deck.update': op('Replace validated deck content at an expected revision; never changes a different deck.', { ...change, deck: deckSchema, brief: briefSchema.nullable().optional() }, async (i, c) => (await service(c)).update(i), { write: true }),
  'deck.archive': op('Reversibly archive or unarchive a deck.', { ...change, archived: z.boolean() }, async (i, c) => (await service(c)).archive(i), { write: true }),
  'deck.duplicate': op('Duplicate a complete deck and brief into an independent deck.', { ...change, title: z.string().min(1).max(140), requestId: z.string().uuid() }, async (i, c) => (await service(c)).duplicate(i), { write: true }),
  'slide.edit': op('Add, update, move or remove a slide with full deck validation.', { ...change, action: z.enum(['add', 'update', 'move', 'remove']), slideId: id.optional(), slide: slidePatch.optional(), position: z.number().int().min(0).max(29).optional() }, async (i, c) => { if (i.action !== 'add' && !i.slideId) throw fault('INVALID_INPUT', 'slideId required.'); if (i.action === 'move' && i.position === undefined) throw fault('INVALID_INPUT', 'position required.'); return (await service(c)).slide(i); }, { write: true }),
  'checkpoint.create': op('Save a durable named recovery point.', { ...change, name: z.string().trim().min(1).max(120) }, async (i, c) => (await service(c)).checkpoint(i), { write: true }),
  'checkpoint.get': op('Preview a checkpoint before restoring it; includes private notes.', { id, checkpointId: id }, async (i, c) => { const cp = (await service(c)).entry(i.id).checkpoints.find(cp => cp.id === i.checkpointId); if (!cp) throw fault('NOT_FOUND', 'Checkpoint not found.', 404); return { checkpoint: cp }; }),
  'checkpoint.restore': op('Restore a previewed checkpoint after explicit confirmation.', { ...change, checkpointId: id, confirm: z.literal(true) }, async (i, c) => (await service(c)).restore(i), { write: true, destructive: true }),
  'deck.validate': op('Validate supplied Fielddeck v1 JSON without saving it.', { deck: deckSchema }, async i => ({ valid: true, deck: validateDeck(i.deck) })),
  'deck.review': op('Editorial checks with content hash; not measured visual fit.', { id }, async (i, c) => (await service(c)).review(i.id)),
  'deck.export': op('Export offline HTML, editable JSON, or brief ZIP. Private formats require explicit consent.', { id, format: z.enum(['html', 'json', 'brief.zip']).default('html'), includePrivate: z.boolean().default(false) }, async (i, c) => (await service(c)).export(i.id, i.format, i.includePrivate)),
  'deck.render': op('Headless whole-deck measured preflight, PDF or a slide PNG. Requires an explicitly installed Chromium browser.', { id, format: z.enum(['preflight', 'pdf', 'png']).default('preflight'), slideNumber: z.number().int().min(1).max(30).default(1) }, async (i, c) => (await service(c)).get(i.id), { after: async (snapshot, input) => (await import('./render.mjs')).render(snapshot, input) }),
  'skills.list': op('List bundled narrative and review skills.', {}, async () => ({ skills: SKILLS.map(id => ({ id, starter: STARTERS.includes(id) })) })),
};
export const product = makeProduct('fielddeck', operations, async root => { await new FielddeckService(root).open(); });
