import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import AxeBuilder from '@axe-core/playwright';
import { startApp, launchBrowser, ARTIFACTS, download, noHorizontalOverflow } from './harness.mjs';

async function audit(page, name) {
  const result = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  await writeFile(path.join(ARTIFACTS, name + '-accessibility.json'), JSON.stringify(result.violations, null, 2));
  assert.deepEqual(result.violations.map(v => ({ id: v.id, targets: v.nodes.map(n => n.target) })), [], `${name} accessibility violations`);
}

function storedZipEntries(bytes) {
  const files = new Map();
  for (let offset = 0; bytes.readUInt32LE(offset) === 0x04034b50;) {
    assert.equal(bytes.readUInt16LE(offset + 8), 0);
    const size = bytes.readUInt32LE(offset + 18), length = bytes.readUInt16LE(offset + 26), extra = bytes.readUInt16LE(offset + 28);
    const name = bytes.subarray(offset + 30, offset + 30 + length).toString();
    const start = offset + 30 + length + extra;
    files.set(name, bytes.subarray(start, start + size));
    offset = start + size;
  }
  return files;
}

async function saved(page) {
  await page.locator('#save-button').click();
  await page.waitForFunction(() => document.querySelector('#save-state').textContent === 'Saved locally');
}

test('Deckforge: edit, persist, reorder, import, export, present, print and responsive accessibility', { timeout: 120000 }, async () => {
  const app = await startApp('deckforge');
  const browser = await launchBrowser();
  const errors = [];
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    const page = await context.newPage();
    page.on('pageerror', e => errors.push(e.message));
    await page.goto(app.url);
    await page.locator('#slide-list > li').first().waitFor();
    assert.equal(await page.locator('#slide-list > li').count(), 6);
    await audit(page, 'deckforge-desktop');
    await page.screenshot({ path: path.join(ARTIFACTS, 'deckforge-desktop.png'), fullPage: true });
    const overflowWarning = page.locator('#qa-list').getByRole('button', { name: /measured preview overflow/ });
    assert.equal(await overflowWarning.count(), 0);
    const overfullTitle = Array(14).fill('Overflow').join('\n');
    await page.locator('#edit-title').fill(overfullTitle);
    await overflowWarning.waitFor();
    await saved(page);
    assert.equal((await (await fetch(app.url + '/api/deck')).json()).deck.slides[0].title, overfullTitle);
    await page.screenshot({ path: path.join(ARTIFACTS, 'deckforge-overflow-warning.png'), fullPage: true });
    await page.locator('[data-slide="1"]').click();
    assert.equal(await overflowWarning.count(), 0);
    await page.locator('[data-slide="0"]').click();
    await overflowWarning.waitFor();
    await page.locator('#edit-title').fill('Evidence before expansion');
    await overflowWarning.waitFor({ state: 'hidden' });
    await page.locator('#speaker-notes').fill('PRIVATE_NOTE_DO_NOT_EXPORT');
    await saved(page);
    await page.reload();
    await page.locator('#edit-title').waitFor();
    assert.equal(await page.locator('#edit-title').inputValue(), 'Evidence before expansion');
    assert.equal(await page.locator('#speaker-notes').inputValue(), 'PRIVATE_NOTE_DO_NOT_EXPORT');
    await page.locator('#duplicate-button').click();
    assert.equal(await page.locator('#slide-list > li').count(), 7);
    await page.locator('#move-up-button').click();
    assert.match(await page.locator('#slide-position').innerText(), /01 \/ 07/);
    await page.locator('#delete-button').click();
    await page.locator('#confirm-cancel').click();
    assert.equal(await page.locator('#slide-list > li').count(), 7);
    await page.locator('#delete-button').click();
    await page.locator('#confirm-accept').click();
    assert.equal(await page.locator('#slide-list > li').count(), 6);
    await page.locator('#add-slide-button').click();
    await page.locator('[data-layout="architecture"]').click();
    await page.locator('#edit-title').fill('Boundaries before integrations');
    assert.equal(await page.locator('#edit-layout').inputValue(), 'architecture');
    await saved(page);
    const jsonPath = await download(page, () => page.locator('#export-json-button').click(), 'deckforge-backup.json');
    const deck = JSON.parse(await readFile(jsonPath, 'utf8'));
    assert.equal(deck.slides.length, 7);
    assert.equal(deck.slides[0].notes, 'PRIVATE_NOTE_DO_NOT_EXPORT');
    const htmlPath = await download(page, () => page.locator('#export-html-button').click(), 'deckforge-presentation.html');
    const html = await readFile(htmlPath, 'utf8');
    assert.ok(!html.includes('PRIVATE_NOTE_DO_NOT_EXPORT'));
    assert.ok(html.includes('Evidence before expansion'));
    const exportPage = await browser.newPage();
    await exportPage.goto('file://' + htmlPath);
    await exportPage.pdf({ path: path.join(ARTIFACTS, 'deckforge-presentation.pdf'), printBackground: true, preferCSSPageSize: true });
    const pdf = await readFile(path.join(ARTIFACTS, 'deckforge-presentation.pdf'));
    assert.equal(pdf.subarray(0, 5).toString(), '%PDF-');
    await page.locator('#present-button').click();
    assert.equal(await page.locator('#present-dialog').isVisible(), true);
    await page.keyboard.press('End');
    assert.equal(await page.locator('#present-position').innerText(), '7 / 7');
    await page.keyboard.press('Home');
    await page.keyboard.press('n');
    assert.equal(await page.locator('#present-notes').innerText(), 'PRIVATE_NOTE_DO_NOT_EXPORT');
    await page.keyboard.press('Escape');
    await page.locator('#import-file').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{oops') });
    await page.locator('#error-banner').waitFor();
    assert.match(await page.locator('#error-banner').innerText(), /Import.*invalid JSON/);
    assert.equal(await page.locator('#slide-list > li').count(), 7);
    await page.locator('#import-file').setInputFiles(jsonPath);
    await page.locator('#confirm-accept').click();
    await saved(page);
    await page.locator('#deck-settings-button').click();
    await page.locator('input[name="theme"][value="cream"]').check();
    await page.getByRole('button', { name: 'Apply settings' }).click();
    await saved(page);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: path.join(ARTIFACTS, 'deckforge-mobile.png'), fullPage: true });
    const dimensions = await noHorizontalOverflow(page);
    assert.ok(dimensions.content <= dimensions.width, JSON.stringify(dimensions));
    await audit(page, 'deckforge-mobile');
    assert.deepEqual(errors, []);
  } finally { await browser.close(); await app.close(); }
});

test('Deckforge: independent library, recovery, complete brief handoff and whole-deck preflight', { timeout: 120000 }, async () => {
  const app = await startApp('deckforge'), browser = await launchBrowser(), errors = [];
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    const page = await context.newPage();
    page.on('pageerror', issue => errors.push(issue.message));
    await page.goto(app.url);
    await page.locator('#edit-title').waitFor();
    const originalId = await page.locator('#deck-switcher').inputValue();
    const original = await (await fetch(app.url + '/api/decks/' + originalId)).json();
    await page.locator('#edit-title').fill('Checkpoint baseline');
    await saved(page);
    await page.locator('#checkpoints-button').click();
    await page.locator('#checkpoint-name').fill('Before the decision');
    await page.locator('#create-checkpoint-button').click();
    await page.locator('[data-preview-checkpoint]').waitFor();
    await audit(page, 'deckforge-checkpoints');
    await page.getByRole('button', { name: 'Close checkpoints', exact: true }).click();
    await page.locator('#edit-title').fill('Changed after checkpoint');
    await page.locator('#undo-button').click();
    assert.equal(await page.locator('#edit-title').inputValue(), 'Checkpoint baseline');
    await page.locator('#redo-button').click();
    assert.equal(await page.locator('#edit-title').inputValue(), 'Changed after checkpoint');
    await page.locator('#checkpoints-button').click();
    await page.locator('[data-preview-checkpoint]').click();
    await page.locator('#checkpoint-preview-dialog').waitFor();
    assert.equal(await page.locator('#checkpoint-preview-slides .slide').count(), original.deck.slides.length);
    await audit(page, 'deckforge-checkpoint-preview');
    await page.locator('#restore-checkpoint-button').click();
    await page.locator('#confirm-cancel').click();
    await page.locator('#restore-checkpoint-button').click();
    await page.locator('#confirm-accept').click();
    await page.locator('#checkpoint-preview-dialog').waitFor({ state: 'hidden' });
    assert.equal(await page.locator('#edit-title').inputValue(), 'Checkpoint baseline');
    await page.locator('#undo-button').click();
    assert.equal(await page.locator('#edit-title').inputValue(), 'Changed after checkpoint');
    await saved(page);
    await page.locator('#starter-button').click();
    await page.locator('#starter-kind').selectOption('fde-pilot-readout');
    await page.locator('#starter-name').fill('Customer gate readout');
    await page.locator('#starter-audience').fill('Customer steering group');
    await page.locator('#starter-decision').fill('Hold expansion until the support gate passes');
    await page.locator('#starter-constraints').fill('No external uploads');
    await page.locator('#starter-gaps').fill('Recovery rehearsal not yet observed');
    await audit(page, 'deckforge-starter');
    await page.getByRole('button', { name: 'Create independent deck', exact: true }).click();
    await page.locator('#starter-dialog').waitFor({ state: 'hidden' });
    const starterId = await page.locator('#deck-switcher').inputValue();
    assert.notEqual(starterId, originalId);
    assert.equal((await (await fetch(app.url + '/api/decks/' + originalId)).json()).deck.slides[0].title, 'Changed after checkpoint');
    await page.locator('#brief-button').click();
    assert.equal(await page.locator('#brief-decision').inputValue(), 'Hold expansion until the support gate passes');
    await audit(page, 'deckforge-agent-brief');
    const zipPath = await download(page, () => page.locator('#export-skill-button').click(), 'deckforge-complete-brief.zip');
    const entries = storedZipEntries(await readFile(zipPath));
    for (const file of ['SKILL.md', 'agents/openai.yaml', 'assets/template.json', 'assets/eval-prompts.json', 'references/deckforge-format.txt']) {
      const actual = await readFile(new URL('../deckforge/skills/fde-pilot-readout/' + file, import.meta.url));
      assert.deepEqual(entries.get('skills/fde-pilot-readout/' + file), actual);
    }
    assert.equal(JSON.parse(entries.get('agent-brief.json')).audience, 'Customer steering group');
    await page.getByRole('button', { name: 'Close agent brief', exact: true }).click();
    await page.locator('#library-button').click();
    await page.locator('#duplicate-deck-title').fill('Isolated copy');
    await page.locator('#duplicate-deck-form button').click();
    await page.locator('#library-dialog').waitFor({ state: 'hidden' });
    const copyId = await page.locator('#deck-switcher').inputValue();
    assert.notEqual(copyId, starterId);
    await page.locator('#edit-title').fill('Copy edits stay separate');
    await saved(page);
    assert.notEqual((await (await fetch(app.url + '/api/decks/' + starterId)).json()).deck.slides[0].title, 'Copy edits stay separate');
    await page.locator('#library-button').click();
    await page.locator(`[data-archive-deck="${copyId}"]`).click();
    await page.locator('#confirm-accept').click();
    await page.waitForFunction(() => !document.querySelector('#archive-state').hidden);
    await audit(page, 'deckforge-library');
    await page.getByRole('button', { name: 'Close library', exact: true }).click();
    assert.equal(await page.locator('#edit-title').isDisabled(), true);
    await page.locator('#deck-switcher').selectOption(originalId);
    await page.waitForFunction(() => document.querySelector('#edit-title').value === 'Changed after checkpoint');
    assert.equal(await page.locator('#undo-button').isDisabled(), true);
    await page.locator('[data-slide="1"]').click();
    await page.locator('#edit-title').fill(Array(14).fill('Overflow').join('\n'));
    await page.locator('[data-slide="0"]').click();
    await page.locator('#review-all-button').click();
    await page.locator('#preflight-status[data-state="current"]').waitFor();
    const reportPath = await download(page, () => page.locator('#export-review-button').click(), 'deckforge-whole-deck-preflight.json');
    const report = JSON.parse(await readFile(reportPath, 'utf8'));
    assert.equal(report.slides.length, original.deck.slides.length);
    assert.equal(report.stale, false);
    assert.equal(report.deckId, originalId);
    assert.equal(report.viewport.width, 1600);
    assert.ok(report.issues.some(issue => issue.code === 'overflow' && issue.slideId === original.deck.slides[1].id));
    const current = await (await fetch(app.url + '/api/decks/' + originalId)).json();
    current.deck.slides[0].title = 'Another window changed this deck';
    const external = await fetch(app.url + '/api/decks/' + originalId, { method: 'PUT', headers: { Origin: app.url, 'Content-Type': 'application/json', 'If-Match': current.revision }, body: JSON.stringify({ deck: current.deck, brief: current.brief }) });
    assert.equal(external.status, 200);
    await page.locator('#library-button').click();
    await page.locator('#library-dialog').waitFor();
    assert.equal(await page.locator('#preflight-status').getAttribute('data-state'), 'stale');
    await page.getByRole('button', { name: 'Close library', exact: true }).click();
    await page.locator('#review-all-button').click();
    await page.locator('#error-banner').waitFor();
    assert.notEqual(await page.locator('#preflight-status').getAttribute('data-state'), 'current');
    await page.reload();
    await page.locator('#edit-title').waitFor();
    assert.equal(await page.locator('#edit-title').inputValue(), 'Another window changed this deck');
    await page.setViewportSize({ width: 390, height: 844 });
    const dimensions = await noHorizontalOverflow(page);
    assert.ok(dimensions.content <= dimensions.width, JSON.stringify(dimensions));
    await audit(page, 'deckforge-library-mobile');
    assert.deepEqual(errors, []);
  } finally { await browser.close(); await app.close(); }
});
