import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { startApp, launchBrowser, ARTIFACTS, download, noHorizontalOverflow } from './harness.mjs';

async function saveEditor(page) {
  await page.locator('#editor-save').click();
  await page.locator('#editor').waitFor({ state: 'hidden' });
}

test('Proofpack: charter, evidence, assessments, attachment redaction, restore and narrow layouts', { timeout: 120000 }, async () => {
  const app = await startApp('proofpack');
  const browser = await launchBrowser();
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto(app.url);
    await page.getByRole('button', { name: 'Create your pilot charter' }).click();
    for (const [key, value] of Object.entries({ customer: 'Example customer', title: 'Controlled routing pilot', objective: 'Validate routing before expansion', owners: 'Pilot owner', startDate: '2026-09-01', endDate: '2026-10-01', internalNotes: 'SECRET_INTERNAL_CHARTER' })) await page.locator('#field-' + key).fill(value);
    await saveEditor(page);
    await page.locator('a[href="#criteria"]').click();
    await page.locator('[data-action="add"][data-section="criteria"]').first().click();
    for (const [key, value] of Object.entries({ name: 'Representative latency', metric: 'p95 latency', baseline: 'Unmeasured', threshold: 'Under 300 ms across 1000 requests', owner: 'Pilot owner', targetDate: '2026-10-01' })) await page.locator('#field-' + key).fill(value);
    assert.equal(await page.locator('#field-visibility').inputValue(), 'internal');
    await page.locator('#field-visibility').selectOption('customer');
    assert.equal(await page.locator('#field-status').count(), 0);
    await saveEditor(page);
    await page.locator('a[href="#evidence"]').click();
    await page.locator('[data-action="add"][data-section="evidence"]').first().click();
    for (const [key, value] of Object.entries({ name: 'Routing result', summary: '240ms observed in a controlled test; expansion unproven', source: 'Local test fixture', owner: 'Test operator' })) await page.locator('#field-' + key).fill(value);
    await page.locator('#field-visibility').selectOption('customer');
    await page.locator('[name="criterionIds"]').check();
    await saveEditor(page);
    await page.getByRole('button', { name: 'Attach a file' }).click();
    await page.locator('#attachment-file').setInputFiles({ name: 'private-evidence.txt', mimeType: 'text/plain', buffer: Buffer.from('SECRET_ATTACHMENT_BYTES') });
    assert.equal(await page.locator('#field-visibility').inputValue(), 'internal');
    await saveEditor(page);
    const data = await (await fetch(app.url + '/api/project')).json();
    assert.equal(data.project.criteria[0].status, 'unassessed');
    assert.equal(data.project.attachments.length, 1);
    await page.locator('a[href="#handover"]').click();
    const htmlPath = await download(page, () => page.getByRole('button', { name: 'Export customer HTML' }).click(), 'proofpack-handover-private-excluded.html');
    const html = await readFile(htmlPath, 'utf8');
    assert.ok(!html.includes('SECRET_INTERNAL_CHARTER'));
    assert.ok(!html.includes('private-evidence.txt'));
    assert.ok(!html.includes(Buffer.from('SECRET_ATTACHMENT_BYTES').toString('base64')));
    assert.ok(html.includes('Representative latency'));
    const backupPath = await download(page, async () => { await page.getByRole('button', { name: 'Private backup…' }).click(); await page.locator('#confirm-proceed').click(); }, 'proofpack-private-backup.json');
    const backup = JSON.parse(await readFile(backupPath, 'utf8'));
    assert.equal(backup.attachmentData.length, 1);
    assert.equal(backup.project.charter.internalNotes, 'SECRET_INTERNAL_CHARTER');
    await page.locator('a[href="#evidence"]').click();
    await page.getByRole('button', { name: 'Make customer-visible' }).click();
    await page.locator('#confirm-proceed').click();
    await page.getByRole('button', { name: 'Make internal' }).waitFor();
    await page.locator('a[href="#handover"]').click();
    const sharedPath = await download(page, () => page.getByRole('button', { name: 'Export customer HTML' }).click(), 'proofpack-handover.html');
    const shared = await readFile(sharedPath, 'utf8');
    assert.ok(shared.includes(Buffer.from('SECRET_ATTACHMENT_BYTES').toString('base64')));
    assert.ok(!shared.includes('SECRET_INTERNAL_CHARTER'));
    const manifestPath = await download(page, () => page.getByRole('button', { name: 'Export manifest' }).click(), 'proofpack-manifest.json');
    const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
    assert.equal(manifest.attachments.length, 1);
    assert.equal(manifest.charter.internalNotes, undefined);
    await page.locator('a[href="#help"]').click();
    await page.getByRole('button', { name: 'Start a blank pilot…' }).click();
    await page.locator('#confirm-proceed').click();
    await page.getByRole('button', { name: 'Create your pilot charter' }).waitFor();
    await page.locator('a[href="#help"]').click();
    await page.getByRole('button', { name: 'Import full backup…' }).click();
    await page.locator('#import-file').setInputFiles(backupPath);
    await page.locator('#confirm-proceed').click();
    await page.getByText('Good work deserves good proof.').waitFor();
    await page.reload();
    await page.getByText('Good work deserves good proof.').waitFor();
    const restored = await (await fetch(app.url + '/api/project')).json();
    assert.equal(restored.project.attachments[0].visibility, 'internal');
    const attachmentResponse = await fetch(app.url + '/api/attachments/' + restored.project.attachments[0].id);
    assert.equal(await attachmentResponse.text(), 'SECRET_ATTACHMENT_BYTES');
    await page.locator('a[href="#help"]').click();
    await page.getByRole('button', { name: 'Import full backup…' }).click();
    await page.locator('#import-file').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{oops') });
    await page.waitForFunction(() => document.querySelector('#toast').textContent.includes('not valid JSON'));
    assert.equal((await (await fetch(app.url + '/api/project')).json()).project.criteria.length, 1);
    await page.locator('a[href="#criteria"]').click();
    await page.getByRole('button', { name: 'Review criterion', exact: true }).click();
    await page.locator('#field-status').selectOption('blocked');
    await page.locator('#field-reviewer').fill('Pilot reviewer');
    await page.locator('#field-rationale').fill('Representative sample incomplete; expand only after validation');
    await saveEditor(page);
    assert.equal((await (await fetch(app.url + '/api/project')).json()).project.criteria[0].status, 'blocked');
    await page.locator('a[href="#decisions"]').click();
    await page.locator('[data-action="add"]').first().click();
    for (const [key, value] of Object.entries({ name: 'Hold expansion', detail: 'Complete the representative test before a rollout decision', owner: 'Pilot reviewer' })) await page.locator('#field-' + key).fill(value);
    await saveEditor(page);
    await page.locator('a[href="#risks"]').click();
    await page.locator('[data-action="add"]').first().click();
    await page.locator('#field-name').fill('Incomplete traffic coverage');
    await page.locator('#field-owner').fill('Pilot owner');
    await saveEditor(page);
    await page.locator('a[href="#checklist"]').click();
    await page.locator('[data-action="add"]').first().click();
    await page.locator('#field-name').fill('Run representative evaluation');
    await page.locator('#field-owner').fill('Pilot owner');
    await saveEditor(page);
    await page.getByRole('button', { name: 'Mark Run representative evaluation complete' }).click();
    await page.getByRole('button', { name: 'Mark Run representative evaluation incomplete' }).waitFor();
    const exportPage = await context.newPage();
    await exportPage.goto('file://' + sharedPath);
    await exportPage.pdf({ path: path.join(ARTIFACTS, 'proofpack-handover.pdf'), printBackground: true });
    await page.setViewportSize({ width: 390, height: 844 });
    for (const route of ['overview', 'criteria', 'evidence', 'risks', 'decisions', 'checklist', 'handover', 'help']) {
      await page.goto(app.url + '/#' + route);
      await page.locator('h1').waitFor();
      const dimensions = await noHorizontalOverflow(page);
      assert.ok(dimensions.content <= dimensions.width, route + ': ' + JSON.stringify(dimensions));
    }
    assert.deepEqual(errors, []);
  } finally { await browser.close(); await app.close(); }
});

test('Proofpack: pilot isolation, review freshness, history, explicit decisions and archive protection', { timeout: 120000 }, async () => {
  const app = await startApp('proofpack'), browser = await launchBrowser(), errors = [];
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    const page = await context.newPage();
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(app.url);
    await page.getByRole('button', { name: 'Explore the fictional sample' }).click();
    await page.locator('#confirm-proceed').click();
    await page.getByText('Good work deserves good proof.').waitFor();
    const firstId = await page.locator('#pilot-select').inputValue();
    const get = async () => (await fetch(app.url + '/api/project?pilot=' + firstId)).json();
    const initial = await get();
    assert.equal(initial.readiness.met, 0);
    assert.ok(initial.readiness.historicalMet > 0);
    const other = await context.newPage();
    await other.goto(page.url());
    await other.locator('a[href="#criteria"]').click();
    await page.locator('a[href="#criteria"]').click();
    await page.locator('[data-action="review-criterion"]').first().click();
    await page.locator('#field-status').selectOption('met');
    await page.locator('#editor-save').click();
    assert.equal(await page.locator('#editor').isVisible(), true);
    await page.locator('#field-reviewer').fill('Synthetic browser reviewer');
    await page.locator('#field-rationale').fill('Synthetic UI fixture: only the supplied controlled sample meets the stated gate.');
    await saveEditor(page);
    let value = await get();
    assert.equal(value.coverage.criteria[0].freshness, 'current');
    assert.equal(value.readiness.met, 1);
    assert.equal(value.project.criteria[0].reviews.length, 2);
    await page.locator('a[href="#evidence"]').click();
    await page.locator('[data-action="edit"][data-id="evidence-run"]').click();
    await page.locator('#field-summary').fill('Changed synthetic sample: measurement protocol requires re-review.');
    await saveEditor(page);
    value = await get();
    assert.equal(value.coverage.criteria[0].freshness, 'changed');
    assert.equal(value.readiness.met, 0);
    assert.equal(value.project.criteria[0].reviews.length, 2);
    await page.locator('a[href="#coverage"]').click();
    assert.match(await page.locator('#main').innerText(), /re-review/);
    await page.locator('a[href="#decisions"]').click();
    await page.locator('[data-action="review-decision"]').first().click();
    await page.locator('#field-outcome').selectOption('proceed');
    await page.locator('#field-reviewer').fill('Synthetic sponsor');
    await page.locator('#field-rationale').fill('UI fixture only: a recorded proceed must not clear unmet gates.');
    await page.locator('#field-conditions').fill('Do not expand until recovery is witnessed.');
    await page.locator('#field-visibility').selectOption('customer');
    await saveEditor(page);
    value = await get();
    assert.equal(value.readiness.met, 0);
    assert.equal(value.decisionReviews[0].freshness, 'current');
    assert.match(await page.locator('#main').innerText(), /not authenticated approval/);
    await page.locator('a[href="#charter"]').click();
    await page.getByRole('button', { name: 'Edit charter', exact: true }).click();
    await page.locator('#field-objective').fill('Changed synthetic scope requires a new pilot decision.');
    await saveEditor(page);
    assert.equal((await get()).decisionReviews[0].freshness, 'changed');
    await other.locator('[data-action="edit"][data-section="criteria"]').first().click();
    await other.locator('#field-threshold').fill('Unsaved stale draft threshold');
    await other.locator('#editor-save').click();
    await other.locator('#form-error').waitFor();
    assert.match(await other.locator('#form-error').innerText(), /another tab/);
    assert.equal(await other.locator('#field-threshold').inputValue(), 'Unsaved stale draft threshold');
    await other.getByRole('button', { name: 'Close editor', exact: true }).click();
    await page.locator('a[href="#library"]').click();
    await page.locator('[data-action="create-pilot"]').click();
    await page.locator('#field-title').fill('Independent second pilot');
    await saveEditor(page);
    const secondId = await page.locator('#pilot-select').inputValue();
    assert.notEqual(secondId, firstId);
    assert.equal(await other.locator('#pilot-select').inputValue(), firstId);
    assert.equal((await (await fetch(app.url + '/api/project?pilot=' + secondId)).json()).project.criteria.length, 0);
    await page.locator('a[href="#handover"]').click();
    const exported = await download(page, () => page.locator('#deckforge-export').click(), 'proofpack-second-pilot.deckforge.json');
    assert.equal(JSON.parse(await readFile(exported, 'utf8')).title, 'Independent second pilot');
    assert.ok(!(await readFile(exported, 'utf8')).includes('Alder & Finch'));
    assert.ok((await page.locator('.preview-frame').getAttribute('src')).includes(secondId));
    await page.locator('a[href="#library"]').click();
    await page.locator(`[data-action="archive-pilot"][data-id="${firstId}"]`).click();
    await page.locator('#confirm-proceed').click();
    await page.locator(`[data-pilot-id="${firstId}"]`).getByText('Archived · read-only').waitFor();
    const beforeArchive = await get();
    const forbidden = await fetch(app.url + '/api/reviews?pilot=' + firstId, { method: 'POST', headers: { Origin: app.url, 'Content-Type': 'application/json' }, body: JSON.stringify({ revision: beforeArchive.project.revision, criterionId: beforeArchive.project.criteria[0].id, status: 'met', reviewer: 'Stale tab', rationale: 'Must be rejected', date: new Date().toISOString().slice(0, 10) }) });
    assert.equal(forbidden.status, 409);
    assert.deepEqual((await get()).project, beforeArchive.project);
    await other.reload();
    await other.locator('.archive-banner').waitFor();
    assert.equal(await other.locator('[data-action="review-criterion"]').first().isDisabled(), true);
    await page.locator(`[data-action="archive-pilot"][data-id="${firstId}"]`).click();
    await page.locator('#confirm-proceed').click();
    await page.locator(`[data-pilot-id="${firstId}"]`).getByText('Active', { exact: true }).waitFor();
    await page.locator('#pilot-select').selectOption(firstId);
    await page.getByText('Good work deserves good proof.').waitFor();
    await page.reload();
    await page.getByText('Good work deserves good proof.').waitFor();
    value = await get();
    assert.equal(value.project.criteria[0].reviews.length, 2);
    assert.equal(value.decisionReviews[0].freshness, 'changed');
    await page.setViewportSize({ width: 390, height: 844 });
    for (const route of ['library', 'coverage', 'decisions']) {
      await page.locator(`a[href="#${route}"]`).click();
      const bounds = await noHorizontalOverflow(page);
      assert.ok(bounds.content <= bounds.width, JSON.stringify({ route, ...bounds }));
    }
    assert.deepEqual(errors, []);
  } finally { await browser.close(); await app.close(); }
});
