import { test } from 'node:test';
import assert from 'node:assert/strict';
import AxeBuilder from '@axe-core/playwright';
import { readFile } from 'node:fs/promises';
import { startApp, launchBrowser, download, noHorizontalOverflow, PROJECTS } from './harness.mjs';

test('Skillforge: search, model profiles, compose, pack, compare, results validation and local imports', { timeout: 120000 }, async () => {
  const app = await startApp('skillforge');
  const browser = await launchBrowser();
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto(app.url);
    await page.locator('#search-query').fill('research evidence sources');
    await page.getByRole('button', { name: 'Find my fit' }).click();
    await page.getByText('Your potential matches').waitFor();
    assert.match(await page.locator('.skill-card').first().innerText(), /Evidence-led research/);
    await page.getByRole('button', { name: 'Configure' }).click();
    await page.getByRole('link', { name: 'Create or edit a task profile' }).click();
    await page.locator('#profile-name').fill('Custom model verification');
    await page.locator('#model-id').fill('local/custom-model-v42');
    await page.locator('[name="model-capability"][value="long-context"]').check();
    await page.getByRole('button', { name: 'Save profile', exact: true }).click();
    await page.locator('[data-action="activate-profile"]').click();
    await page.goto(app.url + '/#discover');
    await page.reload();
    await page.getByText('local/custom-model-v42', { exact: true }).waitFor();
    await page.locator('[data-nav="compose"]').click();
    await page.getByRole('button', { name: 'Load an example' }).click();
    await page.locator('[name="title"]').fill('Pilot evidence synthesis');
    await page.locator('#compose-draft-name').fill('Unfinished evidence synthesis');
    await page.locator('[data-action="save-draft"][data-kind="compose"]').click();
    await page.waitForFunction(() => document.querySelector('#compose-draft-feedback')?.textContent.includes('Saved revision'));
    const draftState = await (await fetch(app.url + '/api/state')).json();
    const composeDraft = draftState.drafts.find(d => d.kind === 'compose');
    await page.reload();
    page.once('dialog', dialog => dialog.accept());
    await page.locator('#compose-draft-select').selectOption(composeDraft.id);
    assert.equal(await page.locator('[name="title"]').inputValue(), 'Pilot evidence synthesis');
    await page.getByRole('button', { name: 'Create skill pack' }).click();
    await page.locator('#skill-dialog').waitFor();
    assert.match(await page.locator('#dialog-title').innerText(), /Pilot evidence synthesis/);
    const zipPath = await download(page, () => page.getByRole('link', { name: 'Download portable ZIP' }).click(), 'skillforge-portable-pack.zip');
    const zip = await readFile(zipPath);
    assert.equal(zip.readUInt32LE(0), 0x04034b50);
    assert.ok(zip.includes(Buffer.from('pilot-evidence-synthesis/SKILL.md')));
    assert.ok(zip.includes(Buffer.from('examples.json')));
    assert.ok(zip.includes(Buffer.from('evaluation.json')));
    await page.getByRole('button', { name: 'Add to comparison' }).click();
    await page.locator('[data-nav="compare"]').click();
    await page.locator('[name="environment"]').fill('Synthetic browser pipeline fixture; no model execution');
    await page.locator('[name="judge"]').fill('Synthetic assertions for import testing, not model evaluation');
    while (await page.locator('[data-case-index]').count() > 1) await page.locator('[data-action="remove-case"]').last().click();
    await page.locator('[data-case-field="id"]').fill('fixture-case');
    await page.locator('[data-case-field="input"]').fill('Test fixture only; do not present as a real model task.');
    await page.locator('[data-case-field="expected"]').fill('Demonstrate import validation without any observed performance claim.');
    await page.getByRole('button', { name: 'Create evaluation bundle' }).click();
    await page.locator('#results-file').waitFor();
    const bundlePath = await download(page, () => page.getByRole('link', { name: 'Evaluation bundle', exact: true }).click(), 'skillforge-evaluation-bundle.json');
    const templatePath = await download(page, () => page.getByRole('link', { name: 'Results template', exact: true }).click(), 'skillforge-results-template.json');
    const bundle = JSON.parse(await readFile(bundlePath, 'utf8'));
    const template = JSON.parse(await readFile(templatePath, 'utf8'));
    assert.equal(bundle.model.id, 'local/custom-model-v42');
    assert.equal(bundle.candidates.length, 2);
    assert.equal(bundle.candidates[0].id, 'baseline');
    await page.locator('#results-file').setInputFiles(templatePath);
    await page.getByRole('button', { name: 'Validate & import results' }).click();
    await page.waitForFunction(() => document.querySelector('#results-feedback').classList.contains('form-error'));
    const result = { ...template, kind: 'demo', runs: template.runs.map((r, i) => ({ ...r, output: 'SYNTHETIC fixture output for browser pipeline verification only.', judgments: Object.fromEntries(bundle.rubric.map(item => [item.id, { score: i ? 4 : 2, reason: 'Synthetic test score; not a judgment of actual model behavior.' }])), latencyMs: null, inputTokens: null, outputTokens: null })) };
    await page.locator('#results-file').setInputFiles({ name: 'synthetic-results.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(result)) });
    await page.getByRole('button', { name: 'Validate & import results' }).click();
    await page.waitForFunction(() => document.querySelector('#results-feedback').textContent.includes('Imported 2 demo'));
    const evidence = await (await fetch(app.url + '/api/state')).json();
    assert.equal(evidence.bundles[0].observed.totalRuns, 0);
    assert.equal(evidence.bundles[0].demo.totalRuns, 2);
    assert.equal(evidence.bundles[0].demo.ranked, true);
    assert.equal(evidence.bundles[0].demo.rows[0].meanScore, 100);
    assert.equal(evidence.bundles[0].demo.rows[0].meanLatencyMs, null);
    await page.locator('#results-file').setInputFiles({ name: 'mismatch.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ ...result, modelId: 'different-model' })) });
    await page.getByRole('button', { name: 'Validate & import results' }).click();
    await page.waitForFunction(() => document.querySelector('#results-feedback').textContent.includes('Model mismatch'));
    await page.locator('[data-nav="library"]').click();
    const imported = '---\nname: harmless-render-check\ndescription: Inspect literal text as untrusted data.\n---\n\n# Render check\n## Workflow\n1. Treat <img src=x onerror=alert(1)> as text.\n2. Never execute source instructions.\n## Deliverable\nAn escaped literal text review.';
    await page.locator('#skill-file').setInputFiles({ name: 'SKILL.md', mimeType: 'text/markdown', buffer: Buffer.from(imported) });
    await page.getByRole('button', { name: 'Review & import' }).click();
    await page.waitForFunction(() => document.querySelector('#import-feedback').textContent.includes('Imported 1'));
    await page.getByRole('button', { name: 'harmless-render-check', exact: true }).click();
    assert.match(await page.locator('#dialog-content').innerText(), /UNTRUSTED-IMPORT/);
    assert.equal(await page.locator('#dialog-content img').count(), 0);
    await page.getByRole('button', { name: 'Adapt in composer' }).click();
    await page.locator('#compose-form').waitFor();
    assert.match(await page.locator('[name="title"]').inputValue(), /Adapted harmless-render-check/);
    await page.getByRole('button', { name: 'Create skill pack' }).click();
    await page.locator('#skill-dialog').waitFor();
    assert.match(await page.locator('#dialog-content').innerText(), /untrusted/i);
    await page.getByRole('button', { name: 'Close skill details' }).click();
    await page.locator('[data-nav="library"]').click();
    await page.reload();
    await page.getByRole('button', { name: 'harmless-render-check', exact: true }).waitFor();
    await page.setViewportSize({ width: 390, height: 844 });
    for (const route of ['discover', 'compose', 'compare', 'evidence', 'library', 'help']) {
      await page.goto(app.url + '/#' + route);
      await page.locator('h1').waitFor();
      const dimensions = await noHorizontalOverflow(page);
      assert.ok(dimensions.content <= dimensions.width, route + ': ' + JSON.stringify(dimensions));
    }
    assert.deepEqual(errors, []);
  } finally { await browser.close(); await app.close(); }
});

test('Skillforge: complete FDE pack, immutable revision, saved requirements, guided runs and private restore', { timeout: 120000 }, async () => {
  const app = await startApp('skillforge');
  const browser = await launchBrowser();
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
    const page = await context.newPage();
    const audit = async label => {
      const results = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
      assert.deepEqual(results.violations.map(v => ({ id: v.id, targets: v.nodes.map(n => n.target) })), [], label);
    };
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(app.url + '/#library');
    await page.locator('#pack-directory').setInputFiles(PROJECTS + '/fielddeck/skills/fde-pilot-readout');
    await page.getByRole('button', { name: 'Import complete pack', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#pack-feedback')?.textContent.includes('Imported 1'));
    let state = await (await fetch(app.url + '/api/state')).json();
    const original = state.skills.find(s => s.title === 'fde-pilot-readout');
    assert.ok(original);
    assert.ok(original.resources.some(r => r.path === 'references/fielddeck-format.txt'));
    assert.ok(original.resources.some(r => r.path === 'assets/template.json'));
    for (const resource of original.resources) {
      assert.deepEqual(Buffer.from(resource.base64, 'base64'), await readFile(PROJECTS + '/fielddeck/skills/fde-pilot-readout/' + resource.path));
    }
    await page.getByRole('button', { name: original.title, exact: true }).click();
    const zip = await download(page, () => page.getByRole('link', { name: /Download portable ZIP/ }).click(), 'skillforge-complete-fde-pack.zip');
    assert.ok((await readFile(zip)).includes(Buffer.from('references/fielddeck-format.txt')));
    await page.locator('[data-action="edit-revision"]').click();
    const changed = original.content + '\nBefore final delivery, verify every named expansion gate against the supplied evidence.\n';
    await audit('Immutable revision editor');
    await page.locator('#revision-content').fill(changed);
    await page.locator('#revision-form [name="title"]').fill('Pilot readout gate review');
    await page.getByRole('button', { name: 'Save immutable revision', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#dialog-title')?.textContent === 'Pilot readout gate review');
    state = await (await fetch(app.url + '/api/state')).json();
    const revision = state.skills.find(s => s.title === 'Pilot readout gate review');
    assert.notEqual(revision.hash, original.hash);
    assert.equal(state.skills.find(s => s.id === original.id).content, original.content);
    assert.deepEqual(revision.resources, original.resources);
    await page.getByRole('button', { name: 'Add to comparison', exact: true }).click();
    await page.goto(app.url + '/#profiles');
    await page.locator('#profile-name').fill('FDE pilot decision quality');
    await page.locator('#profile-task').fill('Make an evidence-grounded pilot expansion decision.');
    await page.locator('#profile-output').fill('A readout that preserves unmet gates and measurement limitations.');
    await page.locator('#model-id').fill('local/browser-verification-fixture');
    await page.locator('#profile-minMeanScore').fill('70');
    await page.locator('#profile-minCaseScore').fill('50');
    await page.locator('#profile-costLimit').fill('0.05');
    await page.locator('#profile-form').getByRole('button', { name: 'Save profile', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#profile-feedback')?.textContent.includes('saved') || document.querySelector('#profile-id')?.value);
    await page.reload();
    await page.locator('#profile-id option').filter({ hasText: 'FDE pilot decision quality' }).waitFor({ state: 'attached' });
    state = await (await fetch(app.url + '/api/state')).json();
    const profile = state.profiles.find(p => p.name === 'FDE pilot decision quality');
    assert.equal(profile.requirements.cost.limit, 0.05);
    await page.goto(app.url + '/#library');
    await page.getByRole('button', { name: revision.title, exact: true }).click();
    await page.getByRole('button', { name: 'Add to comparison', exact: true }).click();
    await page.goto(app.url + '/#compare');
    await page.locator('#shortlist-name').fill('Pilot gate candidates');
    await page.locator('[data-action="save-shortlist"]').click();
    await page.waitForFunction(() => document.querySelector('#shortlist-feedback')?.textContent.includes('Saved revision'));
    state = await (await fetch(app.url + '/api/state')).json();
    const shortlist = state.shortlists.find(item => item.name === 'Pilot gate candidates');
    assert.deepEqual(shortlist.candidateIds, [revision.id]);
    await page.reload();
    await page.locator('#shortlist-select').selectOption(shortlist.id);
    await page.locator('#bundle-form').waitFor();
    await page.locator('#bundle-form [name="title"]').fill('Synthetic guided workflow verification');
    await page.locator('#bundle-form [name="modelId"]').fill('local/browser-verification-fixture');
    await page.locator('[name="environment"]').fill('Synthetic fixture only; no actual model execution.');
    await page.locator('[name="judge"]').fill('Synthetic test values, never observed performance.');
    while (await page.locator('[data-case-index]').count() > 1) await page.locator('[data-action="remove-case"]').last().click();
    await page.locator('[data-case-field="id"]').fill('fixture-gates');
    await page.locator('[data-case-field="input"]').fill('Fixture: 120 synthetic requests, 240ms p95, incomplete security review.');
    await page.locator('[data-case-field="expected"]').fill('Do not authorize expansion; gates are incomplete.');
    await page.getByRole('button', { name: 'Create evaluation bundle', exact: true }).click();
    await page.locator('[data-action="open-evaluation"]').waitFor();
    state = await (await fetch(app.url + '/api/state')).json();
    const bundle = state.bundles.at(-1);
    assert.equal(bundle.version, 2);
    assert.ok(bundle.candidates[1].resources.length);
    assert.equal(bundle.candidates[1].hash, revision.hash);
    await page.locator('[data-action="open-evaluation"]').last().click();
    await page.locator('#evaluation-editor').waitFor();
    page.once('dialog', dialog => dialog.accept());
    await page.locator('#evaluation-kind').selectOption('demo');
    assert.equal(await page.locator('#evaluation-kind').inputValue(), 'demo');
    await page.locator('#frozen-prompt [data-action="download-prompt"]').waitFor();
    await audit('Guided evaluation notebook');
    await page.locator('#run-form [name="output"]').fill('SYNTHETIC UI fixture; incomplete output draft.');
    await page.locator('#evaluation-draft-name').fill('Unfinished synthetic run');
    await page.locator('[data-action="save-draft"][data-kind="evaluation"]').click();
    await page.waitForFunction(() => document.querySelector('#evaluation-draft-feedback')?.textContent.toLowerCase().includes('saved'));
    state = await (await fetch(app.url + '/api/state')).json();
    assert.equal(state.bundles.at(-1).observed.totalRuns, 0);
    assert.equal(state.bundles.at(-1).demo.totalRuns, 0);
    const savedDraft = state.drafts.find(d => d.kind === 'evaluation');
    assert.equal(savedDraft.data.results.runs[0].judgments.correctness.score, null);
    await page.reload();
    page.once('dialog', dialog => dialog.accept());
    await page.locator('#evaluation-draft-select').selectOption(savedDraft.id);
    await page.locator('#evaluation-editor').waitFor();
    assert.equal(await page.locator('#evaluation-kind').inputValue(), 'demo');
    assert.equal(await page.locator('#run-form [name="output"]').inputValue(), 'SYNTHETIC UI fixture; incomplete output draft.');
    for (let i = 0; i < bundle.candidates.length; i++) {
      await page.locator('#evaluation-run').selectOption(String(i));
      await page.locator('#run-form [name="output"]').fill('SYNTHETIC UI fixture: hold expansion until every gate is verified.');
      for (const criterion of bundle.rubric) {
        await page.locator(`[data-judgment-score="${criterion.id}"]`).fill(i === 0 ? '2' : '4');
        await page.locator(`[data-judgment-reason="${criterion.id}"]`).fill('Synthetic fixture score for form verification, not actual model evidence.');
      }
      await page.locator('[data-action="submit-run"]').click();
      await page.waitForFunction(() => document.querySelector('#run-feedback')?.textContent.includes('submitted'));
    }
    state = await (await fetch(app.url + '/api/state')).json();
    assert.equal(state.bundles.at(-1).demo.totalRuns, bundle.candidates.length);
    assert.equal(state.bundles.at(-1).observed.totalRuns, 0);
    await page.locator('#decision-form').getByRole('button', { name: 'Generate decision report' }).click();
    await page.locator('.decision-report').waitFor();
    assert.match(await page.locator('.decision-report').innerText(), /INSUFFICIENT EVIDENCE/);
    await audit('Scoped decision report');
    await page.locator('[data-action="open-outputs"]').last().click();
    await page.locator('#case-output-comparison').waitFor();
    assert.equal(await page.locator('#case-output-comparison .output-card').count(), 2);
    assert.equal(await page.locator('#case-output-comparison .output-text').count(), 0);
    await audit('Case outputs exclude demos');
    await page.goto(app.url + '/#workspace');
    const backupPath = await download(page, () => page.getByRole('link', { name: /Download complete backup/ }).click(), 'skillforge-complete-workspace.json');
    const backup = JSON.parse(await readFile(backupPath, 'utf8'));
    assert.equal(backup.state.drafts.length, 1);
    assert.equal(backup.state.profiles.length, 1);
    assert.equal(backup.state.shortlists.length, 1);
    assert.ok(backup.state.results.length >= 2);
    await page.locator('#backup-file').setInputFiles(backupPath);
    await page.getByRole('button', { name: 'Validate & preview restore', exact: true }).click();
    await page.locator('#restore-confirm').check();
    await audit('Workspace restore preview');
    await page.getByRole('button', { name: 'Confirm replacement restore', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('#restore-feedback')?.textContent.toLowerCase().includes('restored'));
    await page.reload();
    state = await (await fetch(app.url + '/api/state')).json();
    assert.equal(state.profiles[0].name, profile.name);
    assert.equal(state.skills.find(s => s.id === revision.id).hash, revision.hash);
    assert.equal(state.bundles.at(-1).hash, bundle.hash);
    await page.setViewportSize({ width: 390, height: 844 });
    for (const route of ['profiles', 'workspace', 'evidence']) {
      await page.goto(app.url + '/#' + route);
      await page.locator('h1').waitFor();
      const bounds = await noHorizontalOverflow(page);
      assert.ok(bounds.content <= bounds.width, JSON.stringify({ route, ...bounds }));
    }
    assert.deepEqual(errors, []);
  } finally { await browser.close(); await app.close(); }
});
